### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by DiV666** [JReinhold/google-inbox-to-trello#12]
Hi,

I get this error in the console when I click on the button to send an email to trello. According to what I see, the error occurs here:
`userNum = location.href.split('/u/', 2)[1].charAt(0);`

My gmail account is "Google for business" so it does not have in the url **/u/** pattern. The url contains https://inbox.google.com/?pli=1

Can I do something to solve it?

**Comment by JReinhold** [comment]
Oh, I didn't know that was possible.
The only thing you can do is submit a PR, or else I'll fix it within a day.

Thanks for the report.

**Comment by JReinhold** [comment]
@DiV666 I've published a new version `1.0.1` that should hopefully fix the issue. Please try it out, and report if it works.

**Comment by DiV666** [comment]
@JReinhold now its work

Thank you so much
