### ISSUE TITLE
Not working with Google Reminders 

### ISSUE THREAD

**Issue by sungwonida** [JReinhold/google-inbox-to-trello#16]
I'm just wondering but is it normal that google-inbox-to-trello not working with Google Reminders?
The thing is that google-inbox-to-trello works with emails by clicking the button that pops up a dialog.
But when I click the same button next to a reminder, not an email, it doesn't do anything.
I seriously use reminders thus I'm finding out for some workaround to accomplish it(Google Reminders to trello).
Any comments would be appreciated.

**Comment by JReinhold** [comment]
Oh, I hadn't really thought of that use case at all, and haven't tested it. I'm working on a revamped version that should make it easy to make it work with reminders as well. I'll report back during this week how it goes.

**Comment by JReinhold** [comment]
@sungwonida Please try the newly released version 1.1.0, and tell me if it works with your reminders. Your extension should automatically update on Chrome restart.

**Comment by sungwonida** [comment]
Beautiful. Works perfectly for me.
But one thing to comment is the link the extension writes on the Trello-card isn't correct. The link on the card doesn't let me back to the reminder, it shows an empty page saying 'No results'.

**Comment by JReinhold** [comment]
That's odd. Does it do that with all your reminders, or just some of them? Can you please give me an example where it happens? What is the text in the reminder, and what appears in the Inbox search box when you click the link on the card?

**Comment by sungwonida** [comment]
Ah, ok, I found out some phenomena through some tests. In short, it does that('No result') with just some of them, thus it seems like an Inbox By Google's bug. 
It doesn't regard to the text. And when it shows 'No result', the searching in Inbox by Google doesn't work with that query text also.

**Comment by JReinhold** [comment]
Hmm okay. so if I understand correctly, sometimes it doesn't put the correct text in the search field when clicking the link? There might be some characters that is doesn't support, or are encoded wrong in the URL.

Do you use any non-standard-english characters?

**Comment by sungwonida** [comment]
It puts the correct text in the search field. I use Korean for Inbox most, and when I make a card including Korean text through the extension, it works fine. But it happens with some of my old reminders. And the searching text in the reminder doesn’t work in the Inbox searching bar too. Seems like a Google Reminder’s issue.

**Comment by JReinhold** [comment]
oh okay, I see. Yeah doesn't seem like there's anything we can do about it unfortunately.
