### ISSUE TITLE
Done button not working

### ISSUE THREAD

**Issue by sungwonida** [JReinhold/google-inbox-to-trello#17]
Hello.
I'm trying google-inbox-to-trello as a chrome extension. When I finished creating a trello card the dialog shows a green button 'Done' but it isn't working. 

And some information is here,
* Chromium 64.0.3282.167 Built on Ubuntu, running on Ubuntu 16.04
* Google Inbox to Trello 1.0.1

Thanks in advance.

**Comment by JReinhold** [comment]
Thanks for the feedback!
When you say that the Done button doesn't work, do you mean that the card never gets added to Trello? Or does the card get added, but the dialog never closes when you press "Done"?

**Comment by sungwonida** [comment]
The later one. The card got added but the dialog never closes. Thanks.

**Comment by JReinhold** [comment]
Oh okay, yeah I've experienced that myself to. It will be fixed in the next release.

Thanks for reporting! 👍

**Comment by JReinhold** [comment]
@sungwonida Please try the newly released version 1.1.0, and tell me if it fixes the issue. Your extension should automatically update on Chrome restart.

(also, a rating/review on the Webstore would mean alot to me, even if it's just a one star rating)

**Comment by sungwonida** [comment]
It works on 1.1.0. Thanks! (I gave a feedback on the Webstore too)
