### ISSUE TITLE
Can't get it to work....

### ISSUE THREAD

**Issue by VOOM108** [JReinhold/google-inbox-to-trello#23]
No matter what I enter in the ID-fields, clicking "save" does not do anything. I tried the short ID for the board as shown in the URL, as well as the long ID in the JSON. I looked up the ListID in the JSON and added that, still...

**Comment by JReinhold** [comment]
Interesting. Are you using Chrome or Firefox?
When you say it doesn't do anything, do you mean that the ID doesn't get saved in the options, or that the Trello pop-up doesn't care about your IDs?

**Comment by VOOM108** [comment]
This is on Chrome... I enter the IDs in the pop-up, hit "save" and nothing happens. But I must say I am not really sure about the list-ID. Am am new to trello. I added a list "default" to the board "To Do" which I would like to use as the "incoming" list from Inbox. So I searched for "default" in the JSON and added that ID to the pop-up

**Comment by VOOM108** [comment]
Das Board ist privat, spielt das eine Rolle?

**Comment by VOOM108** [comment]
Es scheint, da ist doch das Icon in Inbox. Allerdings nur bei einem der zwei Accounts in denen ich in dem Browser angemeldet bin. 

Kann es sein, dass der Button was speichert, ohne dass das Pop-up verschwindet und eine Rückmeldung da ist, dass es gespeichert ist?

**Comment by VOOM108** [comment]
Sorry, language habit ;) Now it works in both accounts, after another browser restart. 

The point seems to be that there is no feedback at all when saving the IDs, the pop-up stays open and there is no success-message. It seems to work anyway.

**Comment by JReinhold** [comment]
Yes, okay, I understand. Glad it works, sorry about the missing feedback. I'll make it a top priority. :)

Thanks for the feedback, keep it coming! 👍 sorry about the confusion!
